[package]
name = "ykh"
version = "0.1.0"
edition = "2021"
authors = ["Taketo Sano <taketo1024@gmail.com>"]

[features]
all = ["poly", "qint"]
poly = []
qint = []
i128 = []
bigint = []

[workspace]
members = [ 
    "yui-kh"
]

[profile.release]
debug = true
overflow-checks = true

[dependencies]
clap = { version = "4.4.6", features = ["derive", "cargo"] }
csv = "1.2.2"
derive_more = "0.99.17"
indexmap = { version = "2.0.2", features = ["serde"] }
log = "0.4.20"
num-bigint = "0.4.4"
num-traits = "0.2.16"
regex = "1.9.6"
serde_json = "1.0.107"
simplelog = "0.12.1"
string-builder = "0.2.0"
serde = { version = "1.0.188", features = ["derive"] }
cfg-if = "1.0.0"
itertools = "0.11.0"

yui  =         { version = "0.2.0", git = "https://github.com/taketo1024/yui" }
yui-link =     { version = "0.2.0", git = "https://github.com/taketo1024/yui" }
yui-matrix =   { version = "0.2.0", git = "https://github.com/taketo1024/yui" }
yui-homology = { version = "0.2.0", git = "https://github.com/taketo1024/yui" }
# yui  =         { path = "../yui/yui" }
# yui-link =     { path = "../yui/yui-link" }
# yui-matrix =   { path = "../yui/yui-matrix" }
# yui-homology = { path = "../yui/yui-homology" }

yui-kh       = { path = "yui-kh" }

[workspace.dependencies]
yui  =         { version = "0.2.0", git = "https://github.com/taketo1024/yui" }
yui-link =     { version = "0.2.0", git = "https://github.com/taketo1024/yui" }
yui-matrix =   { version = "0.2.0", git = "https://github.com/taketo1024/yui" }
yui-homology = { version = "0.2.0", git = "https://github.com/taketo1024/yui" }
# yui  =         { path = "../yui/yui" }
# yui-link =     { path = "../yui/yui-link" }
# yui-matrix =   { path = "../yui/yui-matrix" }
# yui-homology = { path = "../yui/yui-homology" }
